"""
PARS analytical test report PDF generator.
This is an automated analysis report, not a statutory laboratory certificate.
"""
from typing import Dict, Any, Optional
import os
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable


DISCLAIMER = (
    "This document is an automated PARS analytical test report generated by the PowerNext-AI "
    "condition-monitoring pipeline. It is not a CPRI statutory type-test certificate, regulatory "
    "approval, authorized laboratory endorsement, or signed compliance attestation."
)


def _fmt(value, digits=2, suffix=""):
    if value is None or value == "":
        return "N/A"
    try:
        return f"{float(value):.{digits}f}{suffix}"
    except (TypeError, ValueError):
        return str(value)


def generate_certificate_pdf(record: Dict[str, Any], output_path: str, extra: Optional[Dict[str, Any]] = None) -> str:
    extra = extra or {}
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Heading1"], fontSize=14, alignment=1, spaceAfter=4, textColor=colors.HexColor("#2b2118")
    )
    subtitle = ParagraphStyle(
        "ReportSub", parent=styles["Normal"], fontSize=8, alignment=1, textColor=colors.HexColor("#705b4b"), spaceAfter=8
    )
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=8, leading=11, textColor=colors.HexColor("#2b2118"))
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=7, leading=10, textColor=colors.HexColor("#5c4a3d"))
    warn = ParagraphStyle("Warn", parent=styles["Normal"], fontSize=7, leading=10, textColor=colors.HexColor("#7a3b1e"))

    test_id = str(record.get("Test_ID", "UNKNOWN"))
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    validity = str(record.get("Validity_Label", "Unknown"))
    pred = record.get("Predicted_Reference_Parameter")
    lo = record.get("Interval_95_Lower")
    hi = record.get("Interval_95_Upper")
    width = record.get("Interval_Width")
    if width is None and lo is not None and hi is not None:
        try:
            width = float(hi) - float(lo)
        except (TypeError, ValueError):
            width = None

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title=f"PARS Analytical Report {test_id}",
        author="PowerNext PARS"
    )

    story = []
    story.append(Paragraph("PARS ANALYTICAL TEST REPORT", title_style))
    story.append(Paragraph(
        "PowerNext-AI Condition Monitoring System &bull; Team PARS &bull; Screening analysis report (non-statutory)",
        subtitle
    ))
    story.append(HRFlowable(width="100%", thickness=1.2, color=colors.HexColor("#c4824d")))
    story.append(Spacer(1, 6))

    meta = [
        ["Test ID", test_id, "Report timestamp", ts],
        ["System", "PARS v2.0 (PowerNext-AI)", "Report ID", f"PARS-{test_id}"],
        ["Validity label", validity, "Fault type", str(record.get("Fault_Type", "None"))],
        ["Fault sensor", str(record.get("Fault_Sensor", "None")), "Severity", str(record.get("Fault_Severity", "Normal"))],
    ]
    t = Table(meta, colWidths=[32 * mm, 58 * mm, 38 * mm, 52 * mm])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#ede2d2")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#ede2d2")),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#c4b3a3")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(t)
    story.append(Spacer(1, 8))

    banner_color = colors.HexColor("#d9f2e3") if validity == "Valid" else colors.HexColor("#f8d7d0")
    banner = Table(
        [[Paragraph(
            f"<b>Analytical status:</b> {validity}. "
            f"{record.get('Fault_Reason') or record.get('Reason') or 'No additional diagnostic text.'}",
            body
        )]],
        colWidths=[180 * mm]
    )
    banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), banner_color),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#8c562c")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(banner)
    story.append(Spacer(1, 10))

    story.append(Paragraph("<b>Test conditions</b>", body))
    cond = [
        ["Applied voltage (kV)", _fmt(record.get("Applied_Voltage_kV"), 2),
         "Load current (A)", _fmt(record.get("Load_Current_A"), 2)],
        ["Ambient temperature (°C)", _fmt(record.get("Ambient_Temperature_C"), 2),
         "Test duration (min)", _fmt(record.get("Test_Duration_min"), 1)],
    ]
    ct = Table(cond, colWidths=[45 * mm, 45 * mm, 45 * mm, 45 * mm])
    ct.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#c4b3a3")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f5ede2")),
        ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#f5ede2")),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(ct)
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Sensor readings and physics residuals</b>", body))
    sensors = [
        ["Channel", "Measured rise (°C)", "Residual (°C)", "Channel note"],
        ["Sensor S1", _fmt(record.get("Sensor_S1")), _fmt(record.get("S1_Residual")), "Incoming terminal (schematic)"],
        ["Sensor S2", _fmt(record.get("Sensor_S2")), _fmt(record.get("S2_Residual")), "Outgoing terminal (schematic)"],
        ["Sensor S3", _fmt(record.get("Sensor_S3")), _fmt(record.get("S3_Residual")), "Internal core probe (schematic)"],
        ["Sensor S4", _fmt(record.get("Sensor_S4")), "—", "Auxiliary / uncorrelated channel"],
    ]
    st = Table(sensors, colWidths=[32 * mm, 42 * mm, 38 * mm, 68 * mm])
    st.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#c4824d")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#c4b3a3")),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(st)
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Predicted Reference_Parameter and 95% conformal interval</b>", body))
    pred_tbl = [
        ["Predicted Reference_Parameter", _fmt(pred, 4, " °C")],
        ["95% lower bound", _fmt(lo, 4, " °C")],
        ["95% upper bound", _fmt(hi, 4, " °C")],
        ["Interval width", _fmt(width, 4, " °C")],
        ["Conformal margin (±)", _fmt(record.get("Interval_Margin"), 4, " °C")],
    ]
    pt = Table(pred_tbl, colWidths=[70 * mm, 110 * mm])
    pt.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#c4b3a3")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#ede2d2")),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(pt)
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>Anomaly / fault diagnostics</b>", body))
    fault_tbl = [
        ["Anomaly score", _fmt(record.get("Anomaly_Score"), 4)],
        ["Mahalanobis / multivariate score", _fmt(record.get("Mahalanobis_Distance") or record.get("Multivariate_Anomaly_Score"), 3)],
        ["Cross-sensor inconsistent", str(record.get("Cross_Sensor_Inconsistent", False))],
        ["Contributing sensors", str(record.get("Contributing_Sensors", "None"))],
        ["Fault confidence text", str(record.get("Fault_Confidence", "N/A"))],
        ["Reason", Paragraph(str(record.get("Reason", "")), small)],
    ]
    ft = Table(fault_tbl, colWidths=[55 * mm, 125 * mm])
    ft.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#c4b3a3")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f5ede2")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(ft)
    story.append(Spacer(1, 8))

    shap = record.get("SHAP") or extra.get("shap")
    if shap:
        story.append(Paragraph("<b>Model explanation (Tree SHAP on the weighted ensemble)</b>", body))
        pos = shap.get("top_positive") or []
        neg = shap.get("top_negative") or []
        pos_txt = ", ".join([f"{d.get('feature')} ({d.get('delta_deg_C'):+.3f} °C)" for d in pos[:4]]) or "None"
        neg_txt = ", ".join([f"{d.get('feature')} ({d.get('delta_deg_C'):+.3f} °C)" for d in neg[:3]]) or "None"
        story.append(Paragraph(f"Features that increased predicted hotspot: {pos_txt}", small))
        story.append(Paragraph(f"Features that decreased predicted hotspot: {neg_txt}", small))
        story.append(Paragraph(f"SHAP base value: {_fmt(shap.get('base_value'), 4)} °C", small))
        story.append(Spacer(1, 6))

    story.append(Paragraph("<b>Disclaimer</b>", body))
    story.append(Paragraph(DISCLAIMER, warn))
    story.append(Spacer(1, 10))
    story.append(Paragraph(
        "No handwritten signature, stamp, or certification-body approval is implied. "
        "Interval bounds are split-conformal empirical quantiles of out-of-fold absolute residuals, not a guarantee of coverage on every future specimen.",
        small
    ))

    doc.build(story)
    return output_path


if __name__ == "__main__":
    import json
    import sys
    payload = json.loads(sys.stdin.read())
    out = payload.get("output_path")
    rec = payload.get("record") or {}
    generate_certificate_pdf(rec, out)
    print(json.dumps({"success": True, "path": out}))
